name: Setup MySQL Database

on: [push]

jobs:
  setup-db:
    runs-on: ubuntu-latest

    env:
      APP_PORT: ${{ secrets.APP_PORT }}
      APP_HOST: ${{ secrets.APP_HOST }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}
      SECRET_KEY_JWT: ${{ secrets.SECRET_KEY_JWT }}
      FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
      FRONTEND_URL_BACKOFFICE: ${{ secrets.FRONTEND_URL_BACKOFFICE }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1.1.1
      with:
        mysql-version: '8.0'
        mysql-root-password: ${{ secrets.DB_PASSWORD }}
        mysql-database: ${{ secrets.DB_NAME }}
        mysql-user: ${{ secrets.DB_USER }}
        mysql-password: ${{ secrets.DB_PASSWORD }}

    - name: Run MySQL commands
      run: |
        mysql -h ${{ secrets.DB_HOST }} -P ${{ secrets.DB_PORT }} -u ${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.DB_NAME }};"
