name: Workflow CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_PORT: ${{ secrets.APP_PORT }}
      APP_HOST: ${{ secrets.APP_HOST }}
      DB_HOST: 127.0.0.1
      DB_USER: root
      DB_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}
      SECRET_KEY_JWT: ${{ secrets.SECRET_KEY_JWT }}
      FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
      FRONTEND_URL_BACKOFFICE: ${{ secrets.FRONTEND_URL_BACKOFFICE }}

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v4
      with:
        node-version: 'node'

    - name: Wait for MySQL to be ready
      run: |
        until mysqladmin ping -h "127.0.0.1" --silent; do
          echo 'waiting for mysql...'
          sleep 10
        done

    - name: Check MySQL service status
      run: |
        docker ps

    - name: Run database migrations
      run: |
        mysql -u root -p${{ secrets.DB_ROOT_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.DB_NAME }};"

    - name: Check MySQL logs
      run: |
        docker logs $(docker ps -q --filter ancestor=mysql:5.7)
       # Project stuff   
    - run: npm run setup --if-present
    - run: npm run db:migrate --if-present
    - run: npm run db:seed --if-present
    - run: npm run dev --if-present
    - run: npm run test --if-present
    - run: npm run test --if-present
