name: Setup MySQL Database

on: [push]

jobs:
  setup-db:
    runs-on: ubuntu-latest

    env:
      APP_PORT: ${{ secrets.APP_PORT }}
      APP_HOST: ${{ secrets.APP_HOST }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}
      SECRET_KEY_JWT: ${{ secrets.SECRET_KEY_JWT }}
      FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
      FRONTEND_URL_BACKOFFICE: ${{ secrets.FRONTEND_URL_BACKOFFICE }}
      MYSQL_PWD: ${{ secrets.DB_ROOT_PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install MySQL
      run: sudo apt-get update && sudo apt-get install -y mysql-server

    - name: Start MySQL service
      run: sudo service mysql start

    - name: Set up MySQL database
      run: |
        mysql -u root
        mysql -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.DB_NAME }};"
        mysql -e "CREATE USER IF NOT EXISTS '${{ secrets.DB_USER }}'@'%' IDENTIFIED BY '${{ secrets.DB_PASSWORD }}';"
        mysql -e "GRANT ALL PRIVILEGES ON ${{ secrets.DB_NAME }}.* TO '${{ secrets.DB_USER }}'@'%';"
        mysql -e "FLUSH PRIVILEGES;"
